# Generated by Django 5.1.2 on 2024-10-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sole", "0002_buyer_game_delete_cinema_delete_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="buyer",
        ),
        migrations.AddField(
            model_name="game",
            name="buyer",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
