# Generated by Django 5.1.2 on 2024-10-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sole", "0003_remove_game_buyer_game_buyer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="buyer",
            field=models.CharField(default="", max_length=100),
        ),
    ]
