# Generated by Django 5.1.2 on 2024-10-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sole", "0005_remove_game_buyer_game_buyer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="buyer",
            field=models.ManyToManyField(related_name="games", to="sole.buyer"),
        ),
    ]
